up

diff --git a/.github/workflows/go-ci.yaml b/.github/workflows/go-ci.yaml
--- a/.github/workflows/go-ci.yaml
+++ b/.github/workflows/go-ci.yaml
@@ -127,14 +127,48 @@ jobs:
         run: |
           declare -a unused_deps=()
           find . -name go.mod -execdir go mod tidy \;
-          declare git_status=$(git status --porcelain)
+          declare git_status
+          git_status="$(git status --porcelain)"
           if [ -n "${git_status}" ]; then
             for file in $(echo "${git_status}" | awk '{print $2}'); do
-              if [ "${file}" == "go.mod" ]; then
-                unused_deps+=($(git diff --name-only "${file}"))
-                echo "Unused dependencies found in ${file}"
+              if [[ "${file}" == *"go.mod" ]]; then
+                unused_deps+=("$(git diff --name-only "${file}")")
+                echo "::error file=${file}::Unused dependencies found in go.mod"
               fi
             done
+          fi
+          if [ ${#unused_deps[@]} -gt 0 ]; then
+            exit 1
+          fi
+
+  check-gomod-name:
+    name: Check go.mod name
+    needs: setup-shared-go-cache
+    permissions:
+      contents: read
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@v4
+      - name: Check go.mod name
+        id: check-go-mod-name
+        run: |
+          declare github_base_domain="github.com"
+          declare -a go_mod_file_bad_name=()
+          declare -a go_mod_files
+          mapfile -t go_mod_files < <(find . -name 'go.mod' | sed 's|./||')
+          for go_mod_file in "${go_mod_files[@]}"; do
+            go_mod_dir=$(dirname "${go_mod_file}")
+            go_mod_name=$(awk '/module/ {print $2}' "${go_mod_file}")
+            expected_go_mod_name="${github_base_domain}/${GITHUB_REPOSITORY}/${go_mod_dir}"
+            if [[ "${go_mod_name}" != "${expected_go_mod_name}" ]]; then
+              echo "::error file=${go_mod_file}::go mod name should be ${expected_go_mod_name}"
+              go_mod_file_bad_name+=("${go_mod_file}")
+            fi
+          done
+          if [ ${#go_mod_file_bad_name[@]} -gt 0 ]; then
+            exit 1
           fi
 
   lint:
