up

diff --git a/.github/workflows/go-cd-issueops.yaml b/.github/workflows/go-cd-issueops.yaml
--- a/.github/workflows/go-cd-issueops.yaml
+++ b/.github/workflows/go-cd-issueops.yaml
@@ -16,6 +16,7 @@ jobs:
     if: ${{ github.event.issue.pull_request }}
     runs-on: ubuntu-latest
     outputs:
+      inner_base_ref: ${{ steps.get-base-ref.outputs.base_ref }}
       continue: ${{ steps.override-outputs.outputs.continue }}
       command: ${{ steps.override-outputs.outputs.command }}
       sha: ${{ steps.override-outputs.outputs.sha }}
@@ -27,11 +28,19 @@ jobs:
     permissions:
       pull-requests: write
     steps:
-      - run: |
-          echo ${{ github.event.issue.body }}
-          echo ${{ github.event.issue.pull_request }}
-          echo ${{ github.event.issue.pull_request.base.ref }}
-      - run: exit 1
+      - name: Get base ref
+        id: get-base-ref
+        run: |
+          declare base_ref
+          base_ref="$(gh api \
+            --jq '.base.ref' \
+            repos/{owner}/{repo}/pulls/${{ github.event.issue.number }})"
+          if [ -z "${base_ref}" ]; then
+            echo "Failed to determine base ref, got ${base_ref}"
+            exit 1
+          fi
+          echo "Base ref is ${base_ref}"
+          echo "base_ref=${base_ref}" >> "${GITHUB_OUTPUT}"
       - name: Receive IssueOps preview command
         id: dispatch-issueops-preview-command
         uses: github/command@v2
@@ -51,8 +60,8 @@ jobs:
         with:
           command: .up
           param_separator: ' '
-          skip_reviews: true
-          skip_ci: true
+          skip_reviews: ${{ steps.get-base-ref.outputs.base_ref == 'main' && 'false' || 'true' }}
+          skip_ci: ${{ steps.get-base-ref.outputs.base_ref == 'main' && 'false' || 'true' }}
           permissions: write,admin
           reaction: eyes
           failure_reaction: x
