up

diff --git a/.github/workflows/go-pulumi.yaml b/.github/workflows/go-pulumi.yaml
--- a/.github/workflows/go-pulumi.yaml
+++ b/.github/workflows/go-pulumi.yaml
@@ -112,27 +112,42 @@ jobs:
       - name: Checkout
         id: checkout
         uses: actions/checkout@v4
+      # - name: Start deployment
+      #   id: start-deployment
+      #   env:
+      #     GH_TOKEN: ${{ github.token }}
+      #   run: |
+      #     deployment_id="$(gh api \
+      #       --jq '.id' \
+      #       --method POST \
+      #       repos/{owner}/{repo}/deployments \
+      #       -f ref="${{ inputs.ref }}" \
+      #       -f task='deploy' \
+      #       -f required_contexts\[\] \
+      #       -f environment="${{ inputs.base_ref }}" \
+      #       -f description="Deploy request from IssueOps, initiated by ${{ github.actor }}")"
+      #     if [ -z "${deployment_id}" ]; then
+      #       echo "Failed to start deployment"
+      #       exit 1
+      #     fi
+      #     echo "Deployment started with ID ${deployment_id}"
+      #     echo "deployment_id=${deployment_id}" >> "${GITHUB_OUTPUT}"
+      #     echo "Set deployment ID to ${deployment_id}"
       - name: Start deployment
         id: start-deployment
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          deployment_id="$(gh api \
-            --jq '.id' \
-            --method POST \
-            repos/{owner}/{repo}/deployments \
-            -f ref="${{ inputs.ref }}" \
-            -f task='deploy' \
-            -f required_contexts\[\] \
-            -f environment="${{ inputs.base_ref }}" \
-            -f description="Deploy request from IssueOps, initiated by ${{ github.actor }}")"
-          if [ -z "${deployment_id}" ]; then
-            echo "Failed to start deployment"
-            exit 1
-          fi
-          echo "Deployment started with ID ${deployment_id}"
-          echo "deployment_id=${deployment_id}" >> "${GITHUB_OUTPUT}"
-          echo "Set deployment ID to ${deployment_id}"
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const { data: deployment } = await github.rest.repos.createDeployment({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              ref: context.payload.inputs.ref,
+              task: 'deploy',
+              environment: context.payload.inputs.base_ref,
+              description: `Deploy request from IssueOps, initiated by ${context.actor}`
+            });
+            console.log(`Deployment started with ID ${deployment.id}`);
+            core.setOutput('deployment_id', deployment.id);
 
   build-code:
     name: Build code
