up

diff --git a/.github/workflows/issue-auto-assign.yaml b/.github/workflows/issue-auto-assign.yaml
--- a/.github/workflows/issue-auto-assign.yaml
+++ b/.github/workflows/issue-auto-assign.yaml
@@ -27,6 +27,12 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
+          if [ -f .github/CODEOWNERS ]; then
+            echo "CODEOWNERS file found"
+          else
+            echo "CODEOWNERS file not found"
+            exit 1
+          fi
           declare repo_code_owner
           repo_code_owner="$(cat .github/CODEOWNERS | grep -oP '^\*\s+\K[@a-zA-Z/]+$')"
           if [ -n "${repo_code_owner}" ]; then
